# Generated by Django 5.0.7 on 2025-08-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='created_by',
        ),
    ]
